import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={`flex justify-around min-h-screen`}>
          <div>
              <h1>Side Menu</h1>
          </div>
          <div>{children}</div>
        </div>
      <h1>This is footer</h1>

      </body>
    </html>
  )
}
